# Generated by Django 6.0.6 on 2026-06-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cepa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cabernet Sauvignon, Carmenere, Ensamblaje', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pilares del Monte Gran Reserva', max_length=200)),
                ('cosecha', models.IntegerField(help_text='Año de la cosecha, ej: 2022')),
                ('descripcion', models.TextField(help_text='Notas de cata, maridaje, etc.')),
                ('precio', models.IntegerField(help_text='Precio en pesos chilenos')),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vinos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cepa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinos', to='api.cepa')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
