# Generated by Django 6.0.6 on 2026-06-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cepa_remove_producto_categoria_vino_delete_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Escribe aquí la palabra clave en minúsculas. Ej: historia, clases, proceso', max_length=50, unique=True)),
                ('titulo', models.CharField(help_text='El título que verá el usuario en la página', max_length=200)),
                ('contenido', models.TextField(help_text='El texto principal de esta sección')),
                ('imagen_fondo', models.ImageField(blank=True, help_text='Imagen opcional para acompañar el texto', null=True, upload_to='secciones/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
