# Generated by Django 6.0.6 on 2026-06-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: Taller y Degustación, Masterclass', max_length=100)),
                ('titulo', models.CharField(help_text='Ej: Cata de Vinos Reserva', max_length=200)),
                ('fecha', models.CharField(help_text='Ej: Sábado, 24 de Junio', max_length=100)),
                ('hora', models.CharField(help_text='Ej: 16:00 – 18:00 hrs', max_length=100)),
                ('lugar', models.CharField(help_text='Ej: Cava Principal', max_length=100)),
                ('nivel', models.CharField(blank=True, help_text='Ej: Principiantes', max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(default='#4a1220', help_text='Ej: #4a1220 (rojo) o #d4a017 (dorado)', max_length=20)),
            ],
        ),
    ]
